title: "Control What You Can: Intrinsically Motivated Task-Planning Agent"
description: Supplementary Website

username: Sebastian Blaes
email: sblaes@tue.mpg.de

authors: "Sebastian Blaes, Marin Vlastelica Pogančić, Jia-Jie Zhu, Georg Martius"
